# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

variables:

  ### Variables ###
  nowUserName: '$(NOW_USERNAME)'
  nowPassword: '$(NOW_PASSWORD)'
  nowServer: '$(NOW_SERVER)'
  serviceMap: '$(SERVICE_MAP)'

pool:
  vmImage: 'ubuntu-latest'

stages:

  ### Register Services Stage ###
  - stage: Register_Services
    jobs:
      - job: Register_Services
        steps:  
        - bash: |
            set -x # Echo Commands
            # Register Services
            NOW_API="$(nowServer)/api/sn_sro/service_registration/builder"
            curl -X POST -H "Content-Type: application/json" "$NOW_API" \
            --user $(nowUserName):$(nowPassword) \
            -d @registration/$(serviceMap).json | jq .